[mypy]
python_version = 3.11
strict = True
warn_return_any = True
warn_unused_configs = True

[mypy-yfinance.*]
ignore_missing_imports = True

[mypy-pyarrow.*]
ignore_missing_imports = True

[mypy-alpaca.*]
ignore_missing_imports = True

[mypy-dotenv.*]
ignore_missing_imports = True
